export default {
  CURRENT_EXTENSION_ID: chrome.i18n.getMessage('@@extension_id'),
  FACEBOOK_LIKE_COUNT_URL: 'https://graph.facebook.com/',
  FACEBOOK_SHARE_COUNT_URL: 'https://graph.facebook.com/?id=',
  GOOGLE_PLUS_SHARE_COUNT_URL: 'https://clients6.google.com/rpc?key=YOUR_API_KEY',
  GOOGLE_SEARCH_BASE_URL: 'https://www.google.com/search?q=site%3A',
  KEYWORDS_URL: 'https://serpeeker.herokuapp.com/keywords',
  LINKEDIN_SHARE_COUNT_URL: 'https://www.linkedin.com/countserv/count/share?format=json&url=',
  MIXPANEL_EVENT_URL: 'https://api.mixpanel.com/track/?data=',
  MIXPANEL_TOKEN: '4eb3882957d7327aad9ca130a5749082',
  PINTEREST_SHARE_COUNT_URL: 'https://widgets.pinterest.com/v1/urls/count.json',
  PROD_EXTENSION_ID: 'jbjbbpondgkpmdmkjpnpdfpnnoimehib',
  RANK_URL: 'https://serpeeker.herokuapp.com/rank',
  REAL_FORM_ID: '2f33e21f-3324-437c-8bee-8cc266fc8296',
  RESULT_DATA_URL: 'https://serpeeker.herokuapp.com/result/',
  SEARCH_VOLUME_URL: 'https://serpeeker.herokuapp.com/volume',
  TEST_FORM_ID: '62052d58-3688-4528-81fc-102ea654df06',
  TWITTER_SHARE_COUNT_URL: 'https://cdn.api.twitter.com/1/urls/count.json?url=',
  USER_AGENT: window.navigator.userAgent,
  VERSION_NUMBER: chrome.runtime.getManifest().version
};
